name: Integração Contínua 

on: 
  push:
    branches: ["main", "developer"]
    
    paths: # Para testar o github actions
      - '.github/workflows/ci.yml'
      - 'src/**'
      - 'package.json'

  pull_request:
    branches: ["main", "developer"]
    types: [opened, synchronize, reopened, ready_for_review]
    paths: # Para testar o github actions
      - '.github/workflows/ci.yml'
      - 'src/**'
      - 'package.json'

permissions:
  contents: read

jobs:
  # 1. Job de Instalação e Cache
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

  # 2. Job de Lint (Depende do Setup)
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Run lint
        run: npm run lint

  # 3. Job de Testes (Depende do Setup)
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Run tests
        run: echo "Executando script de teste aqui..."

  # 4. Job de Build (Só roda se o Lint e os Testes passarem)
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
        
      - name: Build
        run: npm run build
        env:
          DATABASE_URL: "file:./dev.db"
          AUTH_URL: http://localhost:3000
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}